{% set name = "ngram" %}
{% set version = "1.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.openfst.org/twiki/pub/GRM/NGramDownload/{{ name }}-{{ version }}.tar.gz
  sha256: 6f1c98ae789a33f9bbcb2239426874b66d5053ca4aba59931c7585b5815164f6

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - openfst =>1.7.8
  run:
    - openfst =>1.7.8

test:
  commands:
    - ngramcount --helpshort >/dev/null || [[ $? == 1 ]]
    - ngraminfo --helpshort >/dev/null || [[ $? == 1 ]]
    - ngrammake --helpshort >/dev/null || [[ $? == 1 ]]
    - ngramshrink --helpshort >/dev/null || [[ $? == 1 ]]
    - ngramsymbols --helpshort >/dev/null || [[ $? == 1 ]]

about:
  home: http://ngram.opengrm.org
  license: Apache-2.0
  license_file: COPYING
  summary: N-Gram modeling
  description: |
    A library for making and modifying n-gram language models encoded as weighted finite-state transducers (FSTs).
  doc_url: http://www.opengrm.org/twiki/bin/view/GRM/NGramQuickTour

extra:
  recipe-maintainers:
    - kylebgorman
